component: aws-iam-role
name: users-permissions
app: tweetscape-app
org: tweetscape

inputs:
  name: ${name}-${stage}-users
  region: us-east-1
  service: lambda.amazonaws.com
  policy: arn:aws:iam::aws:policy/AdministratorAccess
  Resource:
    - ${output:database.arn}
    - ${output:database.arn}/index/*
