component: aws-dynamodb
app: tweetscape-app
org: tweetscape
name: users-table

inputs:
  name: ${name}-${stage}-users
  region: us-east-1
  # Don't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  # Simple, single-table design
  attributeDefinitions:
    - AttributeName: user_id
      AttributeType: S
  keySchema:
    - AttributeName: user_id
      KeyType: HASH
  globalSecondaryIndexes:
    - IndexName: gsi1
      KeySchema:
        - AttributeName: twitter_id
          KeyType: HASH
      Projection:
        ProjectionType: ALL